spawn-tick: 300
disabled-worlds: ""
# spawn chunk radius around player
spawn-radius: 3

max-spawns:
  bat: 0
  blaze: 0
  chicken: 1
  cow: 1
  creeper: 0
  enderman: 0
  ghast: 0
  husk: 0
  horse: 0
  mooshroom: 0
  ocelot: 0
  pig: 1
  polarbear: 0
  rabbit: 1
  stray: 0
  sheep: 1
  skeleton: 0
  spider: 0
  wolf: 0
  zombie: 0
